# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180122_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='caminho',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='projecao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
