# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180122_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='banda',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='inferior_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='inferior_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='nuvens',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='orbita',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='satelite',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='sensor',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='superior_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='superior_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='tamanho_pixel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='tipo_banda',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='tipo_imagem',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='xml',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
